name: Stage WebView Tests

on:
  push:
    paths:
      - "src/**"
      - "tests/playwright/**"
      - "playwright.config.js"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/stage-playwright.yml"
  pull_request:
    paths:
      - "src/**"
      - "tests/playwright/**"
      - "playwright.config.js"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/stage-playwright.yml"

jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Validate Stage secrets
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: npm run ci:validate-secrets

  playwright:
    needs: validate-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: artifacts/playwright-report
          if-no-files-found: warn

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-output
          path: artifacts/playwright-output
          if-no-files-found: warn
